---
apiVersion: batch/v1
kind: Job
metadata:
  name: litmus-openebs-setup
  namespace: litmus 
spec:
  template:
    metadata:
      name: litmus
    spec:
      serviceAccountName: litmus
      restartPolicy: Never
      containers:
      - name: ansibletest
        image: openebs/ansible-runner:ci
        imagePullPolicy: Always
        env: 
          - name: mountPath
            value: /mnt/openebs
          - name: ANSIBLE_STDOUT_CALLBACK
            value: actionable
          - name: MAYA_APISERVER_IMAGE
            value:
          - name: OPENEBS_PROVISIONER_IMAGE
            value:
          - name: OPENEBS_SNAPSHOT_CONTROLLER_IMAGE
            value:
          - name: OPENEBS_SNAPSHOT_PROVISIONER_IMAGE
            value:
          - name: OPENEBS_IO_JIVA_CONTROLLER_IMAGE
            value:
          - name: OPENEBS_IO_JIVA_REPLICA_IMAGE
            value:
          - name: OPENEBS_IO_VOLUME_MONITOR_IMAGE
            value:
          - name: OPENEBS_IO_JIVA_REPLICA_COUNT
            value:
        command: ["/bin/bash"]
        args: ["-c", "ansible-playbook ./operator/0.6/ansible/openebs_setup.yaml -i /etc/ansible/hosts -vv; exit 0"]
        volumeMounts:
          - name: kubeconfig 
            mountPath: /root/admin.conf
            subPath: admin.conf
          - name: logs
            mountPath: /var/log/ansible 
      volumes: 
        - name: kubeconfig
          configMap: 
            name: kubeconfig 
        - name: logs 
          hostPath:
            path: /mnt/openebs
            type: ""
